### ISSUE TITLE
Commands can't be properly used

### ISSUE THREAD

**Issue by Nuvm** [Nuvm/cnb#2]
Some commands, like !rcs, will only trigger with/without a mention, and not the other way around, even if it's supposed to work in both ways.

**Comment by enteryournamehere** [comment]
Works fine for me? ![](http://i.imgur.com/2hED9m2.png)
Maybe it doesn't send it because there is still a cooldown active.
(if the screenshot is not showing: it's here http://i.imgur.com/2hED9m2.png)

**Comment by Nuvm** [comment]
hmm, let me see
imma test it right now

**Comment by Nuvm** [comment]
!rcs works, but !magic or !poke1, !poke2 do not work.

**Comment by enteryournamehere** [comment]
![](http://i.imgur.com/xmTUYRE.png)
^ if not showing: http://i.imgur.com/xmTUYRE.png
They all work for me with a person specified.
!poke1 and !poke2 are not in the switch() for commands without arguments (the first switch). !magic also works without arguments if I un-comment the code for it.

**Comment by Nuvm** [comment]
Hmm, tried the 3 commands which are used in both switches (!adv, !spam and !magic), and they all seem to not work alone. with mentions, they work fine. Quick fyi, plug fixed themselves the html problem related to mentionning yourself using API.

**Comment by Nuvm** [comment]
Fixed a while ago, case closed.
